[[manager.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.append_keymap]]
on = "<Backspace>"
run = "leave"
desc = "Go back to the parent directory"
