os:
    edit: "nvr --remote-tab-wait +'setl bufhidden=wipe' {{filename}}"
    editAtLine: "nvr --remote-tab-wait +'setl bufhidden=wipe | {{line}}' {{filename}}"
    editAtLineAndWait: "nvr --remote-tab-wait +'setl bufhidden=wipe | {{line}}' {{filename}}"
    editInTerminal: true
    openDirInEditor: "nvr --remote-tab-wait +'setl bufhidden=wipe' {{dir}}"

git:
    paging:
        colorArg: always
        pager: delta --dark --paging=never
