require("gui")
require("basics")
require("plugins")
require("utils")
require("globals")

require("plugin-config/dressing")
require("plugin-config/telescope")
require("plugin-config/git")
require("plugin-config/mini")
require("plugin-config/lsp")
require("plugin-config/dap")
require("plugin-config/nvim-cmp")
require("plugin-config/nvim-treesitter")
require("plugin-config/pretty-fold")
require("plugin-config/indent-blankline")
require("plugin-config/discord")
require("plugin-config/theme")

require("keymappings")
