backend = "resized"
color_space = "lab"
palette = "dark16"
check_contrast = true

[templates]
rofi-dark.template = "colors-rofi-dark.rasi"
rofi-dark.target = "~/.cache/wal/colors-rofi-dark.rasi"

gtk.template = "colors-gtk.css"
gtk.target = "~/.cache/wal/colors-gtk.css"

# mako config can't import a file, so we'll use the whole config there
mako.template = "colors-mako"
mako.target = "~/.config/mako/config"

# Compatibility with pywal
wal.template = "wal"
wal.target = "~/.cache/wal/wal"

colors.template = "colors"
colors.target = "~/.cache/wal/colors"

colors-json.template = "colors.json"
colors-json.target = "~/.cache/wal/colors.json"

colors-sh.template = "colors.sh"
colors-sh.target = "~/.cache/wal/colors.sh"

vim.template = "colors-wal.vim"
vim.target = "~/.cache/wal/colors-wal.vim"
