hl.on("hyprland.start", function()
    hl.exec_cmd("openrgb -p default")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("nwg-panel")
    hl.exec_cmd("mako")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("kdeconnectd")
    hl.exec_cmd("kdeconnect-indicator")
    hl.exec_cmd("bun $SETTINGS/scripts/wallpaper.js --schedule &> /tmp/wallpaper.log")
    hl.exec_cmd("arrpc")
end)
