return {
    wallpaper = "{wallpaper}",
    theme_type = "{theme_type}",

    bg = "{bg}",
    dark_bg = "{dark_bg}",
    darker_bg = "{darker_bg}",
    lighter_bg = "{lighter_bg}",

    fg = "{fg}",
    dark_fg = "{dark_fg}",
    light_fg = "{light_fg}",
    bright_fg = "{bright_fg}",
    muted = "{muted}",

    red = "{red}",
    yellow = "{yellow}",
    orange = "{orange}",
    green = "{green}",
    cyan = "{cyan}",
    blue = "{blue}",
    purple = "{magenta}",
    brown = "{brown}",

    bright_red = "{bright_red}",
    bright_yellow = "{bright_yellow}",
    bright_green = "{bright_green}",
    bright_cyan = "{bright_cyan}",
    bright_blue = "{bright_blue}",
    bright_purple = "{bright_magenta}",

    accent = "{accent}",
    cursor = "{cursor}",
    foreground = "{foreground}",
    background = "{background}",
    selection = "{selection}",
    selection_foreground = "{selection_foreground}",
    selection_background = "{selection_background}",

    color0 = "{color0}",
    color1 = "{color1}",
    color2 = "{color2}",
    color3 = "{color3}",
    color4 = "{color4}",
    color5 = "{color5}",
    color6 = "{color6}",
    color7 = "{color7}",
    color8 = "{color8}",
    color9 = "{color9}",
    color10 = "{color10}",
    color11 = "{color11}",
    color12 = "{color12}",
    color13 = "{color13}",
    color14 = "{color14}",
    color15 = "{color15}",
}
